### Metodos utilizados por los usuarios administradores
## utiliza la extension de vscode rest API para probar estas apis.

### obtener datos del admin actual
GET http://localhost:1234/admin/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqdWFuQGFkbWluLmNvbSIsInJvbCI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3NDY0ODk4NTIsImV4cCI6MTc0NjQ5MzQ1Mn0.Konwy_ictf499-PL_01OS5t7EMOIFfpkBW_zgDM4Rsw

### obtener todas las solicitudes SIN ASIGNAR
GET http://localhost:1234/admin/solicitud
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqdWFuQGFkbWluLmNvbSIsInJvbCI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3NDY5NDA3NjAsImV4cCI6MTc0Njk0NDM2MH0.raW6DuZKk5-Zpy6xoWXGChPJTF2swROKP-vhpgDYlgk

### Obtener a los asesores
GET http://localhost:1234/admin/asesores
Authorization: Bearer


### Asigna manualmente una asesoria

POST http://localhost:1234/admin/asesoria
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqdWFuQGFkbWluLmNvbSIsInJvbCI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3NDg4NTMzMDAsImV4cCI6MTc0ODg1NjkwMH0.307omN3WBsiLoIKPmBtVMBFzdA8KtQU0FMH2xCCF9E0
Content-Type: application/json

{
    "id_solicitud": 38,
    "id_asesor": 2
}


#### alterar estado de una solicitud en especifico
PATCH http://localhost:1234/admin/solicitud/?id=3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqdWFuQGFkbWluLmNvbSIsInJvbCI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3NDY0ODUxMDIsImV4cCI6MTc0NjQ4ODcwMn0._lNZsAtb2yN2E-oxbt_-iFjaF433Hm10wXtNU1r6k1E
Content-Type: application/json

{
    "estado": "inactivo"
}


### alterar datos del administrador
PATCH http://localhost:1234/admin/admin
Content-Type: application/json
{
    "nombre": "Maria Tomez 2",
    "email": "Maria@hotmail.com",
    "password": "myPassword33"
}

### eliminar la cuenta del admin actual
DELETE http://localhost:1234/admin/admin

### Eliminar un asesor
DELETE http://localhost:1234/admin/asesores
Authorization: Bearer 