## APIs que utilizaran el usuario, estas son para realizar pruebas.
## Utilizar 

### Obtener datos de el alumno que es usuario actual
GET http://localhost:1234/alumno/alumno
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJsYXVyYUBlc3R1ZGlhbnRlLmNvbSIsInJvbCI6ImFsdW1ubyIsImlhdCI6MTc0NTk1ODMxMiwiZXhwIjoxNzQ1OTYxOTEyfQ.9ykLO0PMnLnxdznbRGwnXerNnq7IkKcCFGu6Z5KN8SQ

### Obtener solicitudes que esten aceptada
GET http://localhost:1234/alumno/solicitud?estado=asignada

### Obtener solicitudes que no hayan sido aceptadas
GET http://localhost:1234/alumno/solicitud?estado=pendiente

### Agregar solicitud
POST http://localhost:1234/alumno/solicitud
content-Type: application/json
Authorization: Bearer <eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJsYXVyYUBlc3R1ZGlhbnRlLmNvbSIsInJvbCI6ImFsdW1ubyIsImlhdCI6MTc0NTk1NDAxOSwiZXhwIjoxNzQ1OTU3NjE5fQ.u6exkXhCUDCpXJAbVlb39aGcsC0L9FDiofokZFHqPdU> 

{
    "modalidad": "en_linea",
    "tema": "calculo integral",
    "fecha_limite": "13-4-2025",
    "observaciones": "ninguna",
}

### Respuesta del alumno segun la encuesta TODO
POST http://localhost:1234/alumno/encuesta
Content-Type: application/json
{
  
}

### Editar atributos del alumno
PUT http://localhost:1234/alumno/alumno
Content-Type: application/json
{
    "nombre": "Juan Perez",
    "curso": "Ingenieria de Software",
    "telefono": "1234567890",
    "matricula": "01234567",
    "password": "miPassword33"
}

DELETE http://localhost:1234/alumno/alumno