## APIs que utilizaran el usuario, estas son para realizar pruebas.
## Utilizar 

### Obtener datos de el alumno que es usuario actual
GET http://localhost:1234/alumno/alumno
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJsYXVyYUBlc3R1ZGlhbnRlLmNvbSIsInJvbCI6ImFsdW1ubyIsImlhdCI6MTc0NTk1ODMxMiwiZXhwIjoxNzQ1OTYxOTEyfQ.9ykLO0PMnLnxdznbRGwnXerNnq7IkKcCFGu6Z5KN8SQ

### Obtener solicitudes que esten aceptada
GET http://localhost:1234/alumno/solicitud?estado=activo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJhbDIyNzYwNTc1QGl0ZS5lZHUubXgiLCJyb2wiOiJhbHVtbm8iLCJpYXQiOjE3NDc5NDYzNzIsImV4cCI6MTc0Nzk0OTk3Mn0.q8NXsqKYTdPsvohUOJUIdRnSULOT_JLp9Ynhezhy7Mc
### Obtener solicitudes que no hayan sido aceptadas
GET http://localhost:1234/alumno/solicitud?estado=pendiente

### Agregar solicitud
POST http://localhost:1234/alumno/solicitud
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJsYXVyYUBlc3R1ZGlhbnRlLmNvbSIsInJvbCI6ImFsdW1ubyIsImlhdCI6MTc0NjA1NTE5NiwiZXhwIjoxNzQ2MDU4Nzk2fQ.RH00-XnCAveZ_vh2xEQrZAgR_Bv0jFNRUwmC6A5fe0U

{
    "id": 4,
    "estudiante_id": 2,
    "asesor_id": 2,
    "tema": "Cálculo vectorial",
    "observaciones": "Necesito ayuda con integrales dobles",
    "fecha_limite": "2025-05-10",
    "modalidad": "presencial",
    "nivel_urgencia": "alta",
    "estado": "inactivo"
}

### Editar atributos del alumno
PATCH http://localhost:1234/alumno/alumno
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZW1haWwiOiJhbDIyNzYwNTc1QGl0ZS5lZHUubXgiLCJyb2wiOiJhbHVtbm8iLCJpYXQiOjE3NDY3NDY0NjUsImV4cCI6MTc0Njc1MDA2NX0.dXyZMR4CmdfEBFhnnYqSdUD6LhEF3bvH3D9BHmcLp_Q

{
    "nombre": "Diego Soto Flores",
    "password": "1234"
}

### Eliminar alumno
DELETE http://localhost:1234/alumno/alumno
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJsYXVyYUBlc3R1ZGlhbnRlLmNvbSIsInJvbCI6ImFsdW1ubyIsImlhdCI6MTc0NjA2NTA1OCwiZXhwIjoxNzQ2MDY4NjU4fQ.c5fps3oGrko-UzgmZRUIvQpLEv68aE4-H8uQbAy4cac
