### APIs de referencia y prueba a utilizar en el proyecto utilizando la extensión REST Client de Visual Studio Code.
## estas son las utilizadas por los Asesores desde su paguina.

### Obtener datos de la cuenta del asesor
GET http://localhost:1234/asesores/asesores
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjYXJsb3NAYXNlc29yLmNvbSIsInJvbCI6ImFzZXNvciIsImlhdCI6MTc0NjQ5NzQ4MSwiZXhwIjoxNzQ2NTAxMDgxfQ.0hDBujg1dk-3rqoCkdZYQa4_CTwji3Vv9salETuBXkE

### Agregar mensaje 
## TODO

### Agregar comentario respecto a una asesoria
POST http://localhost:1234/asesoria
Content-Type: application/json
{
    "id_solicitud": 1,
    "comentario": "Comentario de prueba"
}

### editar datos del asesor
PATCH http://localhost:1234/asesores/asesores
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjYXJsb3NAYXNlc29yLmNvbSIsInJvbCI6ImFzZXNvciIsImlhdCI6MTc0NjQ5ODMzMiwiZXhwIjoxNzQ2NTAxOTMyfQ.uvP1tR21Z3SfjU7LiXXbTVqB51AZMAkB0f4xdmRV82c
Content-Type: application/json

{
  "nombre": "Carlos Torres Fernandez",
  "area_especializacion": "Ingenieria de Software",
  "disponibilidad": "Lunes-Jueves"
}

###
PATCH http://localhost:1234/asesores/asesorias/?id=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjYXJsb3NAYXNlc29yLmNvbSIsInJvbCI6ImFzZXNvciIsImlhdCI6MTc0NjQ5ODMzMiwiZXhwIjoxNzQ2NTAxOTMyfQ.uvP1tR21Z3SfjU7LiXXbTVqB51AZMAkB0f4xdmRV82c
Content-Type: application/json

{
  "estado": "asignada",
  "fecha_atencion": "2025-05-05",
  "hora_inicial": "09:00:00",
  "hora_final": "12:30:00",
  "total_horas": 3.50,
  "porcentaje_cumplimiento": 85.75,
  "requiere_sesiones": 1
}


### borrar cuenta del asesor
DELETE http://localhost:1234/asesores/asesor

