### APIs de referencia y prueba a utilizar en el proyecto utilizando la extensión REST Client de Visual Studio Code.
## estas son las utilizadas por los Asesores desde su paguina.

### Obtener datos de la cuenta del asesor
GET http://localhost:1234/asesores/asesores

### Agregar mensaje 
## TODO

### Agregar comentario respecto a una asesoria
POST http://localhost:1234/solicitud
Content-Type: application/json
{
    "id_solicitud": 1,
    "comentario": "Comentario de prueba"
}

### editar datos del asesor
PUT http://localhost:1234/asesores/asesores
Content-Type: application/json
{
    "nombre": "Emilio Sanshez",
    "area_especializacion": "Ingenieria de Software",
    "email": "EmilioSanshez@hotmail.com",
    "password": "myPassword33"
    //"disponibilidad": "", !! por determinar su inclusion
}

PATCH http://localhost:1234/asesores/asesorias
Content-Type: application/json
{
  "estado": "asignada",
  "fecha_atencion": "2025-05-05",
  "hora_inicial": "09:00:00",
  "hora_final": "12:30:00",
  "total_horas": 3.50,
  "porcentaje_cumplimiento": 85.75,
  "requiere_sesiones": 1
}


### borrar cuenta del asesor
DELETE http://localhost:1234/asesores/asesor

