### Metodo utilizado para probar los mensajes

POST http://localhost:1234/mensajes/crear
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJhbDIyNzYwNTc1QGl0ZS5lZHUubXgiLCJyb2wiOiJhbHVtbm8iLCJpYXQiOjE3NDg1MDkyODIsImV4cCI6MTc0ODUxMjg4Mn0.PP9KWkO8_ymNjGUj48Kj1ROmMS7adNc6c33Knl6INBA
Content-Type: application/json

{
    "id_asesoria": "26",
    "id_receptor": "5",
    "receptor_tipo": "asesor",
    "contenido": "Arre, saludones"
}

### Metodo para obtener los chats del usuario, Unicamente con el token se recuperan los chats
GET http://localhost:1234/mensajes/chats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJhbDIyNzYwNTc1QGl0ZS5lZHUubXgiLCJyb2wiOiJhbHVtbm8iLCJpYXQiOjE3NDg1MDkyODIsImV4cCI6MTc0ODUxMjg4Mn0.PP9KWkO8_ymNjGUj48Kj1ROmMS7adNc6c33Knl6INBA
Content-Type: application/json


### Metodo para obtener los mensajes de un chat

POST http://localhost:1234/mensajes/mensajes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJhbDIyNzYwNTc1QGl0ZS5lZHUubXgiLCJyb2wiOiJhbHVtbm8iLCJpYXQiOjE3NDg1MDkyODIsImV4cCI6MTc0ODUxMjg4Mn0.PP9KWkO8_ymNjGUj48Kj1ROmMS7adNc6c33Knl6INBA
Content-Type: application/json

{
    "id_asesoria": "27"
}

### Metodo para actualizar el estado de un mensaje
PUT http://localhost:1234/mensajes/estado
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJhbDIyNzYwNTc1QGl0ZS5lZHUubXgiLCJyb2wiOiJhbHVtbm8iLCJpYXQiOjE3NDg1MDkyODIsImV4cCI6MTc0ODUxMjg4Mn0.PP9KWkO8_ymNjGUj48Kj1ROmMS7adNc6c33Knl6INBA
Content-Type: application/json

{
    "id_mensaje": "1",
    "estado": 2
}