## APIs de prueba relacionadas con sesiones de usuario
## Utiliza extencion de VSC REST Client para probarlas

#Comando para correr el servidor
#npm run dev

## Realizado cuando uno inicia sesion
### Alumno
POST http://localhost:1234/auth/alumno 
Content-Type: application/json

{
    "email": "juan@estudiante.com",
    "password": "contrasenia123"
}

### Asesor
POST http://localhost:1234/auth/asesor    
Content-Type: application/json

{
    "email": "carlos@asesor.com",
    "password": "asesor123"
}

### Administrador
POST http://localhost:1234/auth/administrador
Content-Type: application/json

{
    "email": "juan@admin.com",
    "password": "admin123"
}

## Para agregar una cuenta
### Alumno
POST http://localhost:1234/alumno 
Content-Type: application/json

{
    "nombre": "Juan Lopez",
    "email": "juan@estudiante.com",
    "password": "contrasenia123"
}

### Asesor
POST http://localhost:1234/asesor 
Content-Type: application/json

{
    "nombre": "Emilio Sanshez",
    "area_especializacion": "Ingenieria de Software",
    "email": "EmilioSanshez@hotmail.com",
    "password": "myPassword33"
    //"disponibilidad": "", !! por determinar su inclusion
}

### Admin
POST http://localhost:1234/administrador 
Content-Type: application/json

{
    "nombre": "Maria Tomez",
    "email": "Maria@hotmail.com",
    "password": "myPassword33"
}