### Metodos utilizados por los usuarios administradores
## utiliza la extension de vscode rest API para probar estas apis.

### obtener datos del asesor actual
GET http://localhost:1234/admin/admin

### obtener todas las solicitudes
GET http://localhost:1234/solicitud

#### alterar estado de una solicitud en especifico
PATCH http://localhost:1234/solicitud/?id=5

### eliminar la cuenta del admin actual
DELETE http://localhost:1234/admin/admin
